FROM node:22.12-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV DATABASE_URL="postgresql://user:pass@localhost:5432/dummy"
RUN npx prisma generate
RUN npm run build  

EXPOSE 8080
CMD ["npm", "run", "start"]
